spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/luozhihi/cloud_config.git

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8079/eureka/
    register-with-eureka: true
